@startuml
class com.mycompany.projecttest2.App
class com.mycompany.projecttest2.LoginController
class com.mycompany.projecttest2.MainWindowBookingController
class com.mycompany.projecttest2.MovieData
class com.mycompany.projecttest2.Recipe
class java.io.File
class java.io.FileInputStream
class java.io.IOException
class java.net.MalformedURLException
class java.net.URL
class java.text.ParseException
class java.text.SimpleDateFormat
class java.time.LocalDate
class java.time.LocalTime
class java.util.ArrayList
class java.util.Arrays
class java.util.Base64
class java.util.Date
class java.util.List
class java.util.Optional
class java.util.ResourceBundle
class javafx.application.Application
class javafx.beans.property.IntegerProperty
class javafx.collections.FXCollections
class javafx.collections.ObservableList
class javafx.collections.transformation.FilteredList
class javafx.collections.transformation.SortedList
class javafx.event.ActionEvent
class javafx.event.EventHandler
class javafx.event.EventType
class javafx.fxml.FXMLLoader
class javafx.scene.Node
class javafx.scene.Parent
class javafx.scene.Scene
class javafx.scene.control.Alert
class javafx.scene.control.Alert.AlertType
class javafx.scene.control.Button
class javafx.scene.control.ButtonType
class javafx.scene.control.ComboBox
class javafx.scene.control.DatePicker
class javafx.scene.control.Label
class javafx.scene.control.PasswordField
class javafx.scene.control.Spinner
class javafx.scene.control.SpinnerValueFactory
class javafx.scene.control.TableColumn
class javafx.scene.control.TableView
class javafx.scene.control.TextField
class javafx.scene.control.cell.PropertyValueFactory
class javafx.scene.image.Image
class javafx.scene.image.ImageView
class javafx.scene.input.MouseEvent
class javafx.scene.layout.AnchorPane
class javafx.stage.FileChooser
class javafx.stage.FileChooser.ExtensionFilter
class javafx.stage.Stage
class javafx.stage.StageStyle
@enduml